ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG UID=1000
ARG GID=1000

RUN apt-get -y update && \
    apt-get install --no-install-recommends -y \
	openocd && \
    apt-get clean -y && \
	apt-get autoremove --purge -y && \
	rm -rf /var/lib/apt/lists/*

# Create 'user' account
RUN useradd -l -m -s /bin/bash -u $UID user

# Make 'user' default on launch
USER user
