ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

ARG USERNAME=user
ARG UID=1000
ARG GID=1000

# Install openocd
RUN <<EOF
    apt-get -y update
    apt-get install --no-install-recommends -y openocd sudo
    apt-get clean -y
	apt-get autoremove --purge -y
	rm -rf /var/lib/apt/lists/*
EOF

# Create user account
RUN <<EOF
	# Remove 'ubuntu' user to free UID 1000
	userdel -r ubuntu || true

	# Create user group and user account
	groupadd -g $GID -o $USERNAME
	useradd -u $UID -m -g $USERNAME -G plugdev $USERNAME

    # Ensure sudoers directory exists
    mkdir -p /etc/sudoers.d

	# Add user account to sudoers
	echo $USERNAME ' ALL = NOPASSWD: ALL' > /etc/sudoers.d/$USERNAME
	chmod 0440 /etc/sudoers.d/$USERNAME
EOF

# Make 'user' default on launch
USER user
