name: Build and publish a NCS Zephyr Docker images

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: irnas/ncs-zephyr

jobs:
  publish:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        variant:
          - ncs_version: "v2.2.0"
          - ncs_version: "v2.3.0"
          - ncs_version: "v2.4.3"
          - ncs_version: "v2.5.3"
          - ncs_version: "v2.6.1"
          - ncs_version: "v2.7.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CI image
        id: push-ci
        uses: docker/build-push-action@v5
        with:
          file: ./ncs-zephyr/Dockerfile
          target: ci
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.ncs_version }}-ci:${{ inputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.ncs_version }}-ci:latest
          build-args: |
            NCS_SDK_VERSION=${{ matrix.variant.ncs_version }}

      - name: Build and push Dev image
        id: push-dev
        uses: docker/build-push-action@v5
        with:
          file: ./ncs-zephyr/Dockerfile
          target: dev
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.ncs_version }}-dev:${{ inputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.ncs_version }}-dev:latest
          build-args: |
            NCS_SDK_VERSION=${{ matrix.variant.ncs_version }}
