name: Build and publish a Vanilla Zephyr Docker images

on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: irnas/vanilla-zephyr

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      # Don't fail the all builds if one of them fails.
      fail-fast: false
      matrix:
        variant:
          - zephyr_version: "v3.6.0"
            zephyr_sdk_version: "0.16.8"
            mcuboot_version: "a4eda30f5b0cfd0cf15512be9dcd559239dbfc91"
          - zephyr_version: "v3.7.1"
            zephyr_sdk_version: "0.16.9"
            mcuboot_version: "ea2410697dd0262edec041a0ccb07fdbde7c1aff"
          - zephyr_version: "v4.0.0"
            zephyr_sdk_version: "0.17.0"
            mcuboot_version: "f74b77cf7808919837c0ed14c2ead3918c546349"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push CI image
        id: push-ci
        uses: docker/build-push-action@v6
        with:
          file: ./vanilla-zephyr/Dockerfile.ci
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.zephyr_version }}-ci:${{ inputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.zephyr_version }}-ci:latest
          build-args: |
            ZEPHYR_VERSION=${{ matrix.variant.zephyr_version }}
            ZEPHYR_SDK_VERSION=${{ matrix.variant.zephyr_sdk_version }}
            MCUBOOT_VERSION=${{ matrix.variant.mcuboot_version }}

      - name: Build and push Dev image
        id: push-dev
        uses: docker/build-push-action@v6
        with:
          file: ./vanilla-zephyr/Dockerfile.dev
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.zephyr_version }}-dev:${{ inputs.release_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.zephyr_version }}-dev:latest
          build-args: |
            ZEPHYR_VERSION=${{ matrix.variant.zephyr_version }}
            ZEPHYR_SDK_VERSION=${{ matrix.variant.zephyr_sdk_version }}
            MCUBOOT_VERSION=${{ matrix.variant.mcuboot_version }}
            BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.variant.zephyr_version }}-ci:${{ inputs.release_version }}
